export type IberiaUserModel = {
  uuid: string;
  name: string;
  firstFlightDate: string;
  firstFlightFrom: string;
  firstFlightTo: string;
  firstFlightClass: string;
  yearsTogether: number;
  favouriteDestinations: string;
  visitedCountries: number;
  traveledKms: string;
  traveledAroundEarth: number;
  traveledHours: number;
  traveledTime: number;
  traveledUnitTime: string;
  mostUsedPlane: string;
  mostTraveledZones: string;
  lastFlightTime: number;
  lastFlightUnitTime: string;
  lastFlightDate: string;
  lastFlightTo: string;
  totalAvios: string;
};
